# Generated by Django 5.2.6 on 2025-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='temp_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
