# Generated by Django 5.2.6 on 2026-01-14 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverification_temp_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
