# Generated by Django 5.2.6 on 2025-12-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="lang",
            field=models.CharField(default="python", max_length=50),
        ),
    ]
