# Generated by Django 5.2.6 on 2025-12-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField()),
                ("expected_output", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="courses.task",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
