# Generated by Django 5.2.6 on 2025-12-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_testcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_exam",
            field=models.BooleanField(default=False),
        ),
    ]
