# Generated by Django 5.2.6 on 2026-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_is_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="input_data",
            field=models.TextField(blank=True),
        ),
    ]
