# Generated by Django 6.0.1 on 2026-01-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_testcase_input_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_olimpiad",
            field=models.BooleanField(default=False),
        ),
    ]
