# Generated by Django 6.0.1 on 2026-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_end_time_course_is_olimpiad"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="show_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
